### ISSUE TITLE
TASK: remove python-pytest-xdist from ELN buildroot

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#125]
### What does the ELN SIG need to do?
* python-pytest-xdist was retired from c9s and presumably unwanted (although not explicitly listed as such) in RHEL 10.  It pulls in a bunch of other unwanted dependencies that were either not in c9s or retired therefrom (python-execnet, python3-docs, python-zope-*, and others).  It should be removed from the ELN buildroot -- either by disabling tests on affected packages (particularly where tests require other unwanted deps), or removing pytest `--numprocesses=auto` arguments -- preferably before the initial import of 10.

Current status: https://tiny.distro.builders/view-rpm--view-eln--python3-pytest-xdist.html

Many of the listed packages at the Buildroot levels are in the process of being removed through other means, so for starters please focus on Required, Dependency, and Buildroot Level 1 packages:

- [x] ansible-core: https://src.fedoraproject.org/rpms/ansible-core/pull-request/22
- [x] pyproject-rpm-macros: https://src.fedoraproject.org/rpms/pyproject-rpm-macros/pull-request/384
- [x] python-alembic: https://src.fedoraproject.org/rpms/python-alembic/pull-request/17
- [x] python-pytest-cov: drop via https://github.com/fedora-eln/eln/issues/128
- [x] python-pytest-randomly: drop via https://github.com/fedora-eln/eln/issues/129
- [x] python-rpmautospec: https://src.fedoraproject.org/rpms/python-rpmautospec/pull-request/4
- [x] python-tox, python-tox-current-env: drop via https://github.com/fedora-eln/eln/issues/126
- [x] python-tpm2-pytss: https://src.fedoraproject.org/rpms/python-tpm2-pytss/pull-request/1
- [x] pythran: https://src.fedoraproject.org/rpms/pythran/pull-request/24
- [x] rpmlint: https://src.fedoraproject.org/rpms/rpmlint/pull-request/30
- [x] scipy: https://src.fedoraproject.org/rpms/scipy/pull-request/27

/cc @hroncok

**Comment by yselkowitz** [comment]
I have a patch to serilaize scipy tests to avoid xdist, but the tests are failing in ELN, compare https://koji.fedoraproject.org/koji/taskinfo?taskID=101499104 and http://koji.fedoraproject.org/koji/taskinfo?taskID=101500330

**Comment by hroncok** [comment]
pythran tests are known to be flaky. Maybe it's transient.

**Comment by yselkowitz** [comment]
Hopefully, after all one would hope that serializing vs parallelizing the tests wouldn't affect the test results, only how long it takes to run them.  I posted my PR, so all the Required and Dependency level packages have PRs now.

**Comment by yselkowitz** [comment]
This package has been removed from the ELN dependency tree.

**Comment by hroncok** [comment]
https://tiny.distro.builders/view-rpm--view-eln--python3-pytest-xdist.html is back in by
https://tiny.distro.builders/view-srpm--view-eln--liboqs.html


Apparently, https://src.fedoraproject.org/rpms/liboqs/c/83f8dbbfe2eb1a87db6a6d4cb59a5f1fbea440e4?branch=rawhide was built as liboqs-0.8.0-3.eln130 but now a previous commit was built as liboqs-0.8.0-3.eln131 7 days ago :shrug:

**Comment by hroncok** [comment]
https://tiny.distro.builders/view-rpm--view-eln--python3-pytest-xdist.html is gone

**Comment by hroncok** [comment]
awscli2 is now pulling in pytest-xdist: https://github.com/minimization/content-resolver-input/pull/1001

**Comment by yselkowitz** [comment]
Unfortunately awscli2 is FTBFS in ELN:

https://github.com/aws/aws-cli/blob/v2/tests/unit/output/test_yaml_output.py#L65

**Comment by hroncok** [comment]
> Unfortunately awscli2 is FTBFS in ELN:
> 
> https://github.com/aws/aws-cli/blob/v2/tests/unit/output/test_yaml_output.py#L65

See https://src.fedoraproject.org/rpms/awscli2/pull-request/52#comment-162951

**Comment by yselkowitz** [comment]
Unfortunately awscli2 is FTBFS in ELN:  https://kojipkgs.fedoraproject.org//work/tasks/5695/107625695/build.log

The cause appears to be a sorting assumption in https://github.com/aws/aws-cli/blob/v2/tests/unit/output/test_yaml_output.py#L65 which frankly looks bogus; what does it matter if the fields are in the same alphabetical order, if you're anyways going to test the parsed output (which is all that should really matter)?

**Comment by yselkowitz** [comment]
Just saw your comment to the PR, I'll follow up there.

**Comment by hroncok** [comment]
awscli2 case fixed, pytest-xdist is gone once again
