### ISSUE TITLE
TASK: remove python-virtualenv from buildroot

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#130]
### What does the ELN SIG need to do?
* python-virtualenv is unwanted in RHEL 10. Therefore, it should be removed from the ELN buildroot preferably before the initial import of c10s. The exact method of removal will vary, but c9s should be used as a guide.

Current status: https://tiny.distro.builders/view-rpm--view-eln--python3-virtualenv.html

Many of the listed packages at the deeper buildroot levels are in the process of being removed through other means, so for starters please focus on Buildroot Level 1 or 2 packages:

- [x] python-build: drop via https://github.com/fedora-eln/eln/issues/126
- [x] python-poetry-core: https://src.fedoraproject.org/rpms/python-poetry-core/pull-request/22
- [x] python-pyproject-api: drop via https://github.com/fedora-eln/eln/issues/126
- [x] python-pytest-cov: drop via https://github.com/fedora-eln/eln/issues/128
- [x] python-setuptools_scm: https://src.fedoraproject.org/rpms/python-setuptools_scm/pull-request/21
- [x] python-tox: drop via https://github.com/fedora-eln/eln/issues/126

/cc @hroncok

**Comment by hroncok** [comment]
Build ia unwanted?

**Comment by yselkowitz** [comment]
They're not in c9s, so unless there is a new compelling need for them, we should aim for exclusion.

**Comment by hroncok** [comment]
They are likely required to build important packages. There is no specific reason to include them explicitly, but if they are pulled in as deps, Python Maint can maintain them.

**Comment by yselkowitz** [comment]
Right now, it looks like python-poetry-core will stay on (at least for a bit) as a BR of python-dns, but python-build should fall off with the rest of the tangled web of unwanted deps.

**Comment by hroncok** [comment]
That is my expectation as well.

I'll talk to the team about putting python-build to CRB explictly because we might need it in the future and adding new packages to RHEL later is super tedious.

**Comment by yselkowitz** [comment]
Not as tedious as getting rid of all these unwanted deps has been, so if you're going to do that, then *please* make sure its deps are pruned first.

**Comment by hroncok** [comment]
Absolutely.

**Comment by yselkowitz** [comment]
This package has been removed from the ELN dependency tree.
