### ISSUE TITLE
TASK: triage all ELN runtime additions compared to c9s

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#137]
### What does the ELN SIG need to do?
With the recent decision to import only runtime packages from ELN to c10s in the first stages, minimization now needs to switch focus from the buildroot -- where much gains (losses?) have already been made (temporary blips aside) -- to the runtime set.  As a starting point, any package in the ELN runtime set that would be new compared to c9s should be triaged as either wanted or unwanted, and if the latter, the necessary action taken to drop it.  As of now, that consists of the following (by SRPM):

- [x] Cython: CRB addition
- [x] Lmod: UNWANTED, suggest environment-variables in fedora-release, drop via https://src.fedoraproject.org/rpms/fedora-release/pull-request/264
- [x] aardvark-dns
- [x] aom: optional dep of libavif, see comment below
- [x] aopalliance: UNWANTED
- [x] apache-commons-collections: new transitive dep of ongres-scram (via ongres-stringprep->velocity)
- [x] argon2: UNWANTED, drop via https://src.fedoraproject.org/rpms/cryptsetup/pull-request/18
- [x] arptables: UNWANTED, drop via https://github.com/minimization/content-resolver-input/pull/872
- [x] can-utils: was planned but never added to c9s, drop via https://github.com/minimization/content-resolver-input/pull/876
- [x] catatonit: bundled in RHEL 9 podman package but listed separately in CR for ELN
- [x] cdrkit: UNWANTED, drop via https://src.fedoraproject.org/rpms/rear/pull-request/3
- [x] cmark: optional dep of evolution (for `ENABLE_MARKDOWN`)
- [x] cockpit-ostree: added by https://github.com/minimization/content-resolver-input/pull/782
- [x] community-mysql: packaged as `mysql` in RHEL, https://github.com/minimization/content-resolver-input/pull/940
- [x] cups-browsed: added by https://github.com/minimization/content-resolver-input/pull/854
- [x] dav1d: optional dep of libavif, see comment below
- [x] dnf5: to replace dnf
- [x] dogtag-pki: replaces `pki-core`
- [ ] duktape: only JS backend option for latest libproxy (where c9s used JSC which is no longer an option), and one of two options for latest polkit (the other being mozjs102, where c9s bundled mozjs78)?
- [x] ebtables: UNWANTED, drop via https://github.com/minimization/content-resolver-input/pull/872
- [x] ecj: dependency of tomcat (see below)
- [x] editorconfig: dependency of gnome-text-editor
- [x] exfatprogs: new dependency of udisks2
- [x] fmt: listed as UNWANTED but is dep of dnf5, paps, and more
- [x] fontawesome4-fonts: replaces fontawesome-fonts as dep of ipa-server
- [x] freeipa: packaged as `ipa` in RHEL, fix via https://src.fedoraproject.org/rpms/fedora-release/pull-request/268
- [X] fsverity-utils: UNWANTED new optional dependency of rpm, drop via https://src.fedoraproject.org/rpms/rpm/pull-request/48
- [x] future: UNWANTED obsolete dependency of python-pefile, drop via https://src.fedoraproject.org/rpms/python-pefile/pull-request/2
- [x] fwupd-efi: deliberate addition
- [x] gcr3: compat package for GNOME apps still based on gtk3
- [x] glibmm2.4: rename from glibmm24
- [x] gnome-browser-connector: rename from chrome-gnome-shell
- [x] gnome-text-editor: replaces gedit
- [ ] gnu-free-fonts: new dep of kernelshark
- [x] golang-github-openprinting-ipp-usb: added by https://github.com/minimization/content-resolver-input/pull/780
- [x] google-noto-sans-cjk-fonts: replaces google-noto-cjk-fonts
- [x] google-noto-sans-cjk-vf-fonts: replaces google-noto-cjk-fonts
- [x] google-noto-serif-cjk-vf-fonts: replaces google-noto-cjk-fonts
- [x] gtkmm3.0: rename from gtkmm30
- [x] gtksourceview5: new dep of GNOME gtk4 based packages (but can we try to drop gtksourceview4?)
- [x] highway: dep of jpegxl
- [x] hunspell-tr: new dep of langpacks-tr
- [x] hyphen-fo
- [x] hyphen-grc
- [x] hyphen-hsb
- [x] hyphen-ia
- [x] hyphen-is
- [x] hyphen-ku
- [x] hyphen-mi
- [x] hyphen-mn
- [x] hyphen-sa
- [x] hyphen-tk
- [x] infinipath-psm: UNWANTED dep of openmpi, drop via https://src.fedoraproject.org/rpms/openmpi/pull-request/12 and https://src.fedoraproject.org/rpms/mpich/pull-request/9
- [ ] iniparser: new dep of ndctl
- [x] jakarta-activation1: ELN j-act (2.y) and j-act1 trade places with c9s j-act (1.y) and j-act2; check with maintainers for c10s naming scheme
- [x] jemalloc: UNWANTED, drop via https://src.fedoraproject.org/rpms/varnish/pull-request/6
- [x] jpegxl: new (optional?) dep of webkitgtk, dep of aom, also includes a GdkPixbuf loader
- [x] koji: UNWANTED, see comment below wrt modulemd-tools, and https://github.com/fedora-eln/eln/issues/127
- [x] kyotocabinet: new dependency of libpinyin (in place of libdb)
- [x] libadwaita: new dependency of GNOME gtk4 apps
- [x] libavif: new (optional) dep of webkitgtk; see comment below
- [x] libb2: new crypto-related dep of python3 and qt6-qtbase, both have builtin/vendored fallbacks, drop via https://src.fedoraproject.org/rpms/python3.11/pull-request/126 https://src.fedoraproject.org/rpms/python3.12/pull-request/63 and https://src.fedoraproject.org/rpms/qt6-qtbase/pull-request/9
- [x] libcloudproviders: UNWANTED dependency of gtk3, nautilus; drop via https://src.fedoraproject.org/rpms/gtk3/pull-request/11 and https://src.fedoraproject.org/rpms/nautilus/pull-request/6
- [x] libcupsfilters: added by https://github.com/minimization/content-resolver-input/pull/854
- [x] libei: new dependency of xorg-x11-server-Xwayland
- [x] libgweather4: replaces libgweather (3.y)
- [x] libiio: was planned but never added to c9s, drop via https://github.com/minimization/content-resolver-input/pull/876
- [ ] liblerc: new optional dependency for libtiff
- [x] liblockfile: present in c9s, missing from CR
- [x] libmanette: UNWANTED dep of webkitgtk, should be dropped with next build
- [x] libmetalink: UNWANTED, drop via https://src.fedoraproject.org/rpms/wget/pull-request/11
- [x] libmysofa: UNWANTED, drop via https://src.fedoraproject.org/rpms/pipewire/pull-request/16
- [x] libportal: new (optional?) dependency of nautilus, totem, xdg-desktop-portal
- [x] libppd: added by https://github.com/minimization/content-resolver-input/pull/854
- [x] librhsm: present in c9s, missing from CR
- [x] libsoup3: replaces libsoup (2.y)
- [x] libtracecmd: split out from trace-cmd
- [x] libunistring1.0: UNWANTED, dropped by libpsl rebuild
- [x] libunwind: UNWANTED, drop via https://src.fedoraproject.org/rpms/mesa/pull-request/27 and sysprof and yelp PRs
- [x] libusb1: replaces libusbx
- [x] libvncserver: UNWANTED, bundled in gnome-remote-desktop in RHEL
- [x] lilv: UNWANTED, drop via https://src.fedoraproject.org/rpms/pipewire/pull-request/16
- [x] linux-atm: rawhide ppp switched from bundled version to system version, use bundled version via https://src.fedoraproject.org/rpms/ppp/pull-request/6
- [x] lprint: added by https://github.com/minimization/content-resolver-input/pull/780
- [x] lua-filesystem: UNWANTED, suggest environment-variables instead of Lmod in fedora-release, drop via https://src.fedoraproject.org/rpms/fedora-release/pull-request/264
- [x] lua-json: UNWANTED, ditto
- [x] lua-lpeg: UNWANTED, ditto
- [x] lua-term: UNWANTED, ditto
- [x] malcontent: UNWANTED dep of flatpak, gnome-control-center, gnome-software (for parental controls), to be dropped
- [x] mingw-binutils: drop from runtime via https://src.fedoraproject.org/rpms/virt-v2v/pull-request/2
- [x] mozjs115: expected to be bundled in gjs (and possibly polkit) like mozjs78 was in c9s
- [x] nodejs20: rename from nodejs
- [x] nss_wrapper
- [x] ntfs-3g: UNWANTED dep of dracut, drop via https://src.fedoraproject.org/rpms/dracut/pull-request/43
- [x] ongres-stringprep: split out from ongres-scram
- [x] opencore-amr: new optional dep of gstreamer1-plugins-ugly-free
- [x] openfec: UNWANTED, drop via https://src.fedoraproject.org/rpms/pipewire/pull-request/16
- [x] orangefs: UNWANTED dep of openmpi, drop via https://src.fedoraproject.org/rpms/openmpi/pull-request/12
- [x] package-notes: for new linker flags
- [x] pappl: added by https://github.com/minimization/content-resolver-input/pull/854
- [x] perl-Clone: dependency of perl-HTTP-Message, perl-Mail-AuthenticationResults
- [ ] perl-Crypt-DES: dependency of perl-Net-SNMP, used bundled DES implementation
- [ ] perl-Net-SNMP: new dependency of perl-SNMP_Session (dependency of mrtg)
- [x] py3c: CRB addition
- [x] pyelftools: dependency of dpdk, in c9s but missing from CR
- [x] python-appdirs: dependency of python-pooch
- [x] python-asn1crypto: dependency of python-tpm2-pytss
- [x] python-charset-normalizer: replaces python-chardet
- [x] python-construct: dependency of python-pybeam
- [x] python-cpio: UNWANTED dep of oscap-anaconda-addon, just dropped
- [x] python-deprecated: UNWANTED? new dependency of python-jwcrypto, https://src.fedoraproject.org/rpms/python-jwcrypto/pull-request/1
- [x] python-docutils: dependency of python-sphinx
- [x] python-imagesize: dependency of python-sphinx
- [x] python-installer: CRB addition
- [x] python-pefile: added by https://github.com/minimization/content-resolver-input/pull/817
- [x] python-podman
- [ ] python-pooch: new optional dependency of scipy
- [x] python-pybeam: UNWANTED? new dependency of rpmlint, https://src.fedoraproject.org/rpms/rpmlint/pull-request/31
- [x] python-pycdio: dependency of lorax, replaces python-pycdlib
- [x] python-pygments: dependency of python-sphinx
- [x] python-pypng: UNWANTED? new dependency of python-qrcode (used by ipa), https://src.fedoraproject.org/rpms/python-qrcode/pull-request/6
- [x] python-pyproject-hooks: CRB addition
- [x] python-pyqt6: replaces python-qt5
- [x] python-pyqt6-sip: ditto
- [x] python-resolvelib: dependency of ansible-core; c9s bundles this but it is also using a newer-than-system python
- [x] python-rpmautospec: PARTIALLY UNWANTED, see https://github.com/fedora-eln/eln/issues/127
- [x] python-schedutils: UNWANTED dependency of tuna, https://src.fedoraproject.org/rpms/tuna/pull-request/7
- [x] python-simpleaudio: UNWANTED *weak* dependency of ibus-table
- [x] python-sphinx: CRB addition
- [x] python-sphinx-theme-alabaster: dependency of python-sphinx
- [x] python-sphinxcontrib-applehelp: dependency of python-sphinx
- [x] python-sphinxcontrib-devhelp: dependency of python-sphinx
- [x] python-sphinxcontrib-htmlhelp: dependency of python-sphinx
- [x] python-sphinxcontrib-jsmath: dependency of python-sphinx
- [x] python-sphinxcontrib-qthelp: dependency of python-sphinx
- [x] python-sphinxcontrib-serializinghtml: dependency of python-sphinx
- [x] python-tomli-w: dependency of rpmlint, replaces write functionality of python-tomli (read functionality is in 3.11 tomllib)
- [x] python-tpm2-pytss: dependency of tpm2-pkcs11-tools
- [x] python-typing-extensions: new dependency of python-alembic, python-qrcode
- [x] python-wheel: CRB addition
- [x] python-wrapt: dependency of python-deprecated (see above)
- [x] python-zstandard: new dependency of rpmlint
- [x] python3.12: replaces python3.9 as "main" python3
- [x] qemu: packaged as `qemu-kvm` in RHEL
- [x] qt6: replaces qt5, same for following components
- [x] qt6-qt3d
- [x] qt6-qt5compat
- [x] qt6-qtbase
- [x] qt6-qtcharts
- [x] qt6-qtconnectivity
- [x] qt6-qtdatavis3d
- [x] qt6-qtdeclarative
- [x] qt6-qtimageformats
- [x] qt6-qtlanguageserver
- [x] qt6-qtlocation
- [x] qt6-qtlottie
- [x] qt6-qtmultimedia
- [x] qt6-qtnetworkauth
- [x] qt6-qtpositioning
- [x] qt6-qtquick3d
- [x] qt6-qtquicktimeline
- [x] qt6-qtremoteobjects
- [x] qt6-qtscxml
- [x] qt6-qtsensors
- [x] qt6-qtserialbus
- [x] qt6-qtserialport
- [x] qt6-qtshadertools
- [x] qt6-qtspeech
- [x] qt6-qtsvg
- [x] qt6-qttools
- [x] qt6-qttranslations
- [x] qt6-qtvirtualkeyboard
- [x] qt6-qtwayland
- [x] qt6-qtwebchannel
- [x] qt6-qtwebsockets
- [x] restore: is in c9s but not listed in CR
- [x] rgb: split out from xorg-x11-server-utils
- [x] rit-ezhuthu-fonts: UNWANTED
- [x] rit-meera-new-fonts: replaces smc-meera-fonts
- [x] rit-panmana-fonts: UNWANTED
- [x] rit-rachana-fonts: replaces smc-rachana-fonts
- [x] rit-sundar-fonts: UNWANTED
- [x] rit-tn-joy-fonts: UNWANTED
- [x] roc-toolkit: UNWANTED, drop via https://src.fedoraproject.org/rpms/pipewire/pull-request/16
- [x] rust-packaging
- [x] rust-rav1e: UNWANTED optional dep of libavif, see comment below
- [x] rust-rpm-sequoia: new dependency of rpm
- [x] rust-sevctl: renamed from sevctl
- [x] sblim-gather
- [x] senamirmir-washra-fonts: UNWANTED
- [x] serafettin-cartoon-fonts: UNWANTED
- [x] serd: UNWANTED, drop via https://src.fedoraproject.org/rpms/pipewire/pull-request/16
- [x] shim-unsigned-x64: not new 
- [x] sil-mingzat-fonts: added font
- [x] smc-anjalioldlipi-fonts: UNWANTED
- [x] smc-dyuthi-fonts: UNWANTED
- [x] smc-raghumalayalamsans-fonts: UNWANTED
- [x] smc-suruma-fonts: UNWANTED
- [x] snowball: replaces and provides libstemmer
- [x] sord: UNWANTED, drop via https://src.fedoraproject.org/rpms/pipewire/pull-request/16
- [x] sratom: UNWANTED, drop via https://src.fedoraproject.org/rpms/pipewire/pull-request/16
- [x] star: present in c9s, missing from CR
- [x] stress: UNWANTED, waiting on systemtap rebuild
- [x] svt-av1: optional dep of libavif, see comment below
- [x] tecla: replaces libgnomekbd
- [x] thrift: UNWANTED, see https://github.com/fedora-eln/eln/issues/135
- [x] tlwg-fonts: replaces thai-scalable-fonts
- [x] tomcat: added to c9s for [rhbz#2160511](https://bugzilla.redhat.com/show_bug.cgi?id=2160511) but seemingly hasn't replaced pki-servlet-engine (the renamed minimal version for pki-core or tomcatjss); CR still lists this as unwanted?
- [x] tslib: new dependency of qt6
- [ ] uchardet: optional dependency of totem-pl-parser
- [x] udftools: new dependency of udisks2
- [x] usbguard-notifier: part of usbguard SRPM in c9s
- [x] vazirmatn-fonts: new default font due to https://src.fedoraproject.org/rpms/langpacks/c/e446ef9db8e63b8962ac0c6b7836e3eef88d54bf ?
- [x] velocity: new transitive dep of ongres-scram (via ongres-stringprep), drop via https://src.fedoraproject.org/rpms/ongres-stringprep/pull-request/1
- [x] vemana2000-fonts: UNWANTED
- [x] vmaf: dep of aom, see comment below
- [x] webkitgtk: rename from webkit2gtk3
- [x] webp-pixbuf-loader: new dep of gnome-backgrounds
- [x] xcb-util-cursor: new dependency of qt6
- [x] xhost: split out from xorg-x11-server-utils
- [x] xmodmap: split out from xorg-x11-server-utils
- [x] xpdf: texlive switched back from poppler, see https://github.com/fedora-eln/eln/issues/53#issuecomment-1594479241
- [x] xprop: previously missing dep of at-spi2-core
- [x] xrandr: split out from xorg-x11-server-utils
- [x] xrdb: split out from xorg-x11-server-utils
- [x] xxhash: optional dependency of rsync and dwz, was added to 9.1 for https://bugzilla.redhat.com/show_bug.cgi?id=2095255 but CR wasn't updated and c9s isn't using it for those packages
- [x] zchunk: UNWANTED result of https://fedoraproject.org/wiki/Changes/Zchunk_Metadata but was dropped from c9s, drop via https://src.fedoraproject.org/rpms/libsolv/pull-request/11

**Comment by hroncok** [comment]
Cython and sphinx at least are expected in CRB only. This means something is pulling it into AppStream/BaseOS? Sorry, I'm from my cellphone, so cannot check much now.

**Comment by yselkowitz** [comment]
@hroncok CR is showing them as CRB, so I'll mark those as expected.  I know you're busy with the 3.12 rebuild, but when you can if you could please review the other python additions above.

**Comment by hroncok** [comment]
We don't maintain all things Python. I'm actually leaving for PTO. Will cc @torsava here.

**Comment by torsava** [comment]
@yselkowitz Indeed, the Python-maint team maintains the Python interpreters and the core Python packages, we don't have the capacity to maintain all Python in Fedora/ELN/RHEL/CentOS. I recommend checking which workloads pull in those dependencies and contacting those teams.

**Comment by yselkowitz** [comment]
Presumably we want some degree of AV1 support in RHEL 10, but libavif (for AVIF support in webkitgtk) currently uses *four* codecs: aom (encode/decode), dav1d (decoder only), rav1e (encode only), svt-av1 (encode only); that seems a bit excessive.  GStreamer supports aom and svt-av1, but the plugins are currently disabled in RHEL builds (based on EL9's lack of AV1).

Therefore, input would be helpful to determine:
1. Should RHEL 10 webkitgtk support AVIF, and if so, which codec(s) should be enabled in libavif?
2. Should RHEL 10 GStreamer support AV1, and if so, which plugin(s) should be enabled in gstreamer1-plugins-bad-free?

**Comment by yselkowitz** [comment]
libb2 needs to be considered carefully since it is crypto-related.  The two consumers are python3 and qt6-qtbase; the desktop team has told me they will follow whatever decision is made for Python.  Both will use a builtin/vendored copy if a system one isn't present at build time or disabled.  So either this is a case where we use the vendored code on RHEL in order to avoid supporting the standalone library (which customers may try to use themselves in other use cases), or we specifically use the system library (but not ship -devel) in order to consolidate security maintenance.

**Comment by yselkowitz** [comment]
Also, if RHEL 10 will not ship modular content, do we still need to include `modulemd-tools`  (CS System Management workload)?  One part of it requires koji which we don't want in RHEL.  It wouldn't be hard to drop just that part, but if we can drop the whole package, even better.
