### ISSUE TITLE
TASK: drop classic pcre from ELN

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#147]
### What does the ELN SIG need to do?
"Classic" pcre (8.y) -- not to be confused with the current pcre2 (10.y) -- is no longer maintained upstream, and we do not want to support it in RHEL 10.  As such, all dependents need to be ported to pcre2.

Current status: https://tiny.distro.builders/view-rpm--view-eln--pcre-devel.html

- [x] cyrus-imapd: tracked upstream https://github.com/cyrusimap/cyrus-imapd/issues/3861
- [x] golang: unused, drop via https://src.fedoraproject.org/rpms/golang/pull-request/93
- [x] nmap: in progress upstream https://github.com/nmap/nmap/issues/1335
- [x] openscap: tracked upstream https://github.com/OpenSCAP/openscap/issues/1873
- [x] qt5-qtbase (UNWANTED): https://src.fedoraproject.org/rpms/qt5-qtbase/pull-request/18
- [x] qt6-qtbase: https://src.fedoraproject.org/rpms/qt6-qtbase/pull-request/7
- [x] zsh: fixed in upstream master https://github.com/zsh-users/zsh/commit/b62e911341c8ec7446378b477c47da4256053dc0

**Comment by yselkowitz** [comment]
Filed https://src.fedoraproject.org/rpms/cyrus-imapd/pull-request/9 and https://src.fedoraproject.org/rpms/nmap/pull-request/9 to remove the last uses of classic pcre in ELN.

**Comment by yselkowitz** [comment]
The last PR has been merged and is building now for ELN; pcre should fall off of CR in due course.
