### ISSUE TITLE
TASK: fix F39FTBFS

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#153]
### What does the ELN SIG need to do?
The F39 mass rebuild is going to have a number of FTBFS, with Python 3.12 being the first culprit, and gettext-0.22 a runner-up.  Any failures in the ELN package set will need to be fixed promptly, as the CentOS Stream 10 import is forthcoming and we need all packages to be buildable.

List of all F39FTBFS (although our focus is only on the ELN package set): https://kojipkgs.fedoraproject.org/mass-rebuild/f39-failures.html

- [x] autotrace: https://src.fedoraproject.org/rpms/pstoedit/pull-request/4
- [x] babel: python 3.12 test failure, [upstream issue](https://github.com/python-babel/babel/issues/1005)
- [x] clevis-pin-tpm2: https://src.fedoraproject.org/rpms/clevis-pin-tpm2/pull-request/2
- [x] crash-gcore-command: requires crash build only in f39-rebuild
- [x] crash-trace-command: ditto
- [x] criu: kernel 6.5 regression, https://src.fedoraproject.org/rpms/criu/pull-request/9
- [x] cyrus-sasl: https://src.fedoraproject.org/rpms/cyrus-sasl/pull-request/9
- [x] delve: golang 1.21 issue?
- [x] fcoe-utils: https://src.fedoraproject.org/rpms/fcoe-utils/pull-request/5
- [x] fftw: mpich test errors on s390x only, https://src.fedoraproject.org/rpms/fftw/pull-request/10 ends up avoiding that for ELN
- [x] firefox
- [x] fltk: https://src.fedoraproject.org/rpms/fltk/pull-request/3
- [x] gl-manpages: fixed by maintainer
- [x] gnome-shell: depends on mutter version only in f39-rebuild
- [x] grafana: spurious test failure? retrying
- [x] latex2html: https://src.fedoraproject.org/rpms/latex2html/pull-request/1
- [x] ldapjdk: https://src.fedoraproject.org/rpms/ldapjdk/pull-request/6
- [x] libblkio: https://src.fedoraproject.org/rpms/libblkio/pull-request/3
- [x] libkcapi: cppcheck regression, https://src.fedoraproject.org/rpms/libkcapi/pull-request/30
- [x] libuv: spurious test failure? retrying
- [x] libvirt-glib: https://src.fedoraproject.org/rpms/libvirt-glib/pull-request/2
- [x] lua: s390x test error in new version, [bug 2226537](https://bugzilla.redhat.com/show_bug.cgi?id=2226537)
- [x] man-db
- [x] mariadb: spurious test failure? retrying
- [x] msitools: wixl test data requires update, https://src.fedoraproject.org/rpms/msitools/pull-request/3
- [x] nvme-cli: python3-autopep8 (N/A to ELN) not yet built for 3.12, https://src.fedoraproject.org/rpms/nvme-cli/pull-request/1
- [ ] nvml (UNWANTED)
- [x] podman
- [x] pybind11: https://src.fedoraproject.org/rpms/pybind11/pull-request/8
- [x] pyodbc: (DROPPED) requires porting to current PyUnicode APIs; [upstream issue](https://github.com/mkleehammer/pyodbc/issues/917), [downstream bug](https://bugzilla.redhat.com/show_bug.cgi?id=2155256)
- [ ] python-breathe: doxygen 1.9.7 issue, https://github.com/breathe-doc/breathe/issues/935 (docs are not built in RHEL due to dependencies)
- [x] python-gssapi: Cython 3 issue, https://src.fedoraproject.org/rpms/python-gssapi/pull-request/6
- [x] python-kmod: Cython 3 issue
- [x] python-lxml: Cython 3 issue
- [x] python-setuptools: test failures (tests are not run in RHEL due to dependencies)
- [x] pythran
- [x] qatengine: https://src.fedoraproject.org/rpms/qatengine/pull-request/2
- [x] qt6-*: 6.5.2 update is overlapping with mass rebuild, should sort itself out
- [x] rdma-core: Cython 3 issue, https://src.fedoraproject.org/rpms/rdma-core/pull-request/9
- [ ] rubygem-ronn-ng: [upstream issue](https://github.com/apjanke/ronn-ng/issues/102)
- [x] sblim-sfcc
- [x] scap-security-guide: https://src.fedoraproject.org/rpms/scap-security-guide/pull-request/26
- [x] setools
- [x] slf4j
- [x] speexdsp
- [x] strace: needs update for 6.5 kernel
- [x] sudo: https://src.fedoraproject.org/rpms/sudo/pull-request/26
- [x] tang
- [x] thermald
- [x] thunderbird
- [x] wget: metalink test failures (N/A to ELN)
- [x] whois: GPG verification (N/A to ELN)
- [x] xorg-x11-xtrans-devel

**Comment by yselkowitz** [comment]
@hroncok babel and python-setuptools still FTBFS with Python 3.12.

**Comment by hroncok** [comment]
- setuptools: https://bugzilla.redhat.com/show_bug.cgi?id=2222249
 - babel: https://bugzilla.redhat.com/show_bug.cgi?id=2225718

**Comment by hroncok** [comment]
> * setuptools: https://bugzilla.redhat.com/show_bug.cgi?id=2222249
> * babel: https://bugzilla.redhat.com/show_bug.cgi?id=2225718

Both fixed in rawhide

**Comment by sergiomb2** [comment]
I built python-breathe today
